"""
IntradaySyntheticStore: loads pre-generated .npz synthetic bear episodes from disk
and serves them to IntradayTradingEnv on demand.

Each .npz file must contain:
    stock_features  (n_stocks, lookback+ep_bars, N_FEATURES)   float32
    close_prices    (n_stocks, ep_bars+1)                       float32
    stock_mask      (n_stocks,)                                  float32

Files should be generated by generate_synthetic.py and stored in
  intraday_trader/data/processed/synthetic_episodes/

Usage in env:
    store = IntradaySyntheticStore("intraday_trader/data/processed/synthetic_episodes")
    env   = IntradayTradingEnv(ds, synthetic_store=store, synthetic_ratio=0.30)
"""
from __future__ import annotations
from pathlib import Path

import numpy as np

from src.utils.logging_config import get_logger

log = get_logger("intraday.synthetic_store")


class IntradaySyntheticStore:
    """
    Loads all .npz episodes in a directory into memory.
    Call sample(rng) to get a random episode dict.
    """

    def __init__(self, episodes_dir: str, lazy: bool = False):
        self._dir  = Path(episodes_dir)
        self._lazy = lazy
        self._pool: list = []   # list of dicts (or paths if lazy)

        files = sorted(self._dir.glob("*.npz"))
        if not files:
            log.warning(
                "No .npz synthetic episode files found in %s. "
                "Run generate_synthetic.py first.",
                episodes_dir,
            )
            return

        for path in files:
            if lazy:
                self._pool.append(str(path))
            else:
                ep = _load_episode(path)
                if ep is not None:
                    self._pool.append(ep)

        log.info(
            "IntradaySyntheticStore: loaded %d episodes from %s",
            len(self._pool), episodes_dir,
        )

    # ------------------------------------------------------------------
    def __len__(self) -> int:
        return len(self._pool)

    def is_empty(self) -> bool:
        return len(self._pool) == 0

    def sample(self, rng: np.random.Generator) -> dict | None:
        """
        Return a randomly sampled episode dict.
        Keys: stock_features, close_prices, stock_mask
        Returns None if pool is empty.
        """
        if not self._pool:
            return None

        idx = int(rng.integers(0, len(self._pool)))
        item = self._pool[idx]

        if isinstance(item, str):
            # lazy mode: load from disk
            ep = _load_episode(Path(item))
            if ep is None:
                log.warning("Failed to load %s", item)
                return None
            return ep

        return item


# ---------------------------------------------------------------------------
def _load_episode(path: Path) -> dict | None:
    """Load a .npz episode file into a dict of numpy arrays."""
    try:
        data = np.load(str(path))
        ep = {k: data[k] for k in data.files}
        # Validate required keys
        if "stock_features" not in ep or "close_prices" not in ep:
            log.warning("Missing required keys in %s", path.name)
            return None
        return ep
    except Exception as e:
        log.warning("Could not load %s: %s", path.name, e)
        return None
